### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by jjab2020** [enovision/ext-pdf-viewer#1]
Hi friend ,
Thank you very much for this great plugin of pdf viewer,

I have some remarks about integrating this awesome plugins to my project:

I have put the folder ext-pdf-viewer in folder package of extjs application.
and also i have add the this package to app.json and i do sencha app refresh after this step it's ok, but
after that  when i add the Ext.require([
   'Ext.container.Viewport',
   'PdfViewer.singleton.Loader' // this is the one
]); to the app.js and after that i do sencha app refresh i get a error message  failed to find any 
files for Ext.container.Viewport
Any suggestions, Any helps.
Thank you very much
i'm used the project dashboard application generated from folder extjs of version sencha extjs 6.2.0
Have a nice day

**Comment by enovision** [comment]
@jjab2020, 
I have modified the PDF Viewer intensively. Please read the Readme carefully, because some things have changed regarding the loading of the external resources.

After putting the PDF viewer in another test application I found out that some events were not functioning properly. This has been modified. 

It is not required anymore to use the `loader` singleton, this has been taken out completely. All pdf.js external resources are loaded through the package.json.
